//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Use_Service.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fahrenheittocelsiusconversion.azurewebsites.net/", ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fahrenheittocelsiusconversion.azurewebsites.net/IService1/FahrenheitToCels" +
            "ius", ReplyAction="http://fahrenheittocelsiusconversion.azurewebsites.net/IService1/FahrenheitToCels" +
            "iusResponse")]
        double FahrenheitToCelsius(double farenheitDegrees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fahrenheittocelsiusconversion.azurewebsites.net/IService1/FahrenheitToCels" +
            "ius", ReplyAction="http://fahrenheittocelsiusconversion.azurewebsites.net/IService1/FahrenheitToCels" +
            "iusResponse")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double farenheitDegrees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fahrenheittocelsiusconversion.azurewebsites.net/IService1/CelsiusToFahrenh" +
            "eit", ReplyAction="http://fahrenheittocelsiusconversion.azurewebsites.net/IService1/CelsiusToFahrenh" +
            "eitResponse")]
        double CelsiusToFahrenheit(double celsiusDegrees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fahrenheittocelsiusconversion.azurewebsites.net/IService1/CelsiusToFahrenh" +
            "eit", ReplyAction="http://fahrenheittocelsiusconversion.azurewebsites.net/IService1/CelsiusToFahrenh" +
            "eitResponse")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsiusDegrees);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Use_Service.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Use_Service.ServiceReference1.IService1>, Use_Service.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double FahrenheitToCelsius(double farenheitDegrees) {
            return base.Channel.FahrenheitToCelsius(farenheitDegrees);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double farenheitDegrees) {
            return base.Channel.FahrenheitToCelsiusAsync(farenheitDegrees);
        }
        
        public double CelsiusToFahrenheit(double celsiusDegrees) {
            return base.Channel.CelsiusToFahrenheit(celsiusDegrees);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsiusDegrees) {
            return base.Channel.CelsiusToFahrenheitAsync(celsiusDegrees);
        }
    }
}
